# Generated by Django 2.2.4 on 2019-11-04 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_auto_20191103_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='time_of_arrival',
        ),
        migrations.AddField(
            model_name='order',
            name='time_of_arrival',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
